//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkSender.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BulkSenderEntities : DbContext
    {
        public BulkSenderEntities()
            : base("name=BulkSenderEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contact> Contact { get; set; }
        public virtual DbSet<Group> Group { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Pattern> Pattern { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
    }
}
