//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkSender.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public Nullable<int> PatternId { get; set; }
        public string GroupIdList { get; set; }
        public Nullable<long> TotalReceiver { get; set; }
        public string EmailTitle { get; set; }
        public string EmailBody { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
