//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BulkSender.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting
    {
        public int Id { get; set; }
        public string ObjectType { get; set; }
        public string ItemKey { get; set; }
        public string ItemValue { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsPassword { get; set; }
    }
}
